#!/usr/bin/env python3
"""
Generate pre-recorded audio files for tanpura playback.
Creates 45 files: 3 String 1 notes (P, m, N) × 15 Sa values (G#2 to A#3)

Outputs two formats:
  - OGG Vorbis → output/tanpura/          (Android / Swaramandal)
  - CAF/ALAC   → output/tanpura_caf/       (iOS / iSwarmandal, lossless)
    Requires macOS afconvert (pre-installed on all Macs, not available on Linux).

Harmonic structure extracted from real Calcutta-standard male tanpura recording
via spectral analysis (FFT). Key finding: H7 is the dominant harmonic (1.00),
representing the authentic jawari effect, not H4/H11/H17 as commonly assumed.

Source: https://www.india-instruments.com/tanpura-details/calcutta-standard-male-tanpura.html
Analysis: Extracted String 2 (mid Sa - tonic) harmonics from stable 1-2s segment
Validation: C3 frequency detected at 131.25 Hz (0.3% deviation from 130.81 Hz)

DESIGN NOTE: Asset Generation Strategy
--------------------------------------
Currently, generated assets (45 OGG files, ~6MB) are committed to git.

Tradeoffs:
✅ Fast builds - no generation overhead
✅ Simple setup - no Python dependency for contributors/CI
✅ Guaranteed consistency across all builds
❌ ~6MB in git history (acceptable for now)
❌ Re-tweaking audio params requires re-committing all files

Alternative (future consideration):
- Move to Gradle build task that generates assets at build-time
- Only commit this script, not the generated assets
- Would require Python venv setup in CI/CD and for all contributors
- Consider if synthesis params change frequently or repo size becomes problematic
"""

import subprocess
import tempfile
import numpy as np
from pathlib import Path
import soundfile as sf

# Audio configuration
SAMPLE_RATE = 44100
SUSTAIN_DURATION = 10.0  # seconds per string (increased for smoother looping)
BEAT_INTERVAL = 0.6  # 100 BPM
CYCLE_BEATS = 6
CYCLE_DURATION = BEAT_INTERVAL * CYCLE_BEATS

# Just Intonation ratios
NOTE_RATIOS = {
    "S": 1.0,
    "r": 16.0 / 15.0,
    "R": 9.0 / 8.0,
    "g": 6.0 / 5.0,
    "G": 5.0 / 4.0,
    "m": 4.0 / 3.0,
    "M": 45.0 / 32.0,
    "P": 3.0 / 2.0,
    "d": 8.0 / 5.0,
    "D": 5.0 / 3.0,
    "n": 16.0 / 9.0,
    "N": 15.0 / 8.0,
}

# Sa values from G#2 to A#3 (15 semitones)
SA_FREQUENCIES = {
    "gs2": 103.83,
    "a2": 110.00,
    "as2": 116.54,
    "b2": 123.47,
    "c3": 130.81,
    "cs3": 138.59,
    "d3": 146.83,
    "ds3": 155.56,
    "e3": 164.81,
    "f3": 174.61,
    "fs3": 185.00,
    "g3": 196.00,
    "gs3": 207.65,
    "a3": 220.00,
    "as3": 233.08,
}

# String 1 notes to generate (most common)
STRING1_NOTES = ["P", "m", "N"]

# Harmonic structure extracted from real tanpura recording (String 2 - tonic Sa)
# Source: https://www.india-instruments.com/tanpura-details/calcutta-standard-male-tanpura.html
# Key finding: H7 is dominant (1.00) representing the authentic jawari effect
HARMONICS = [
    (1.0, 0.26),  # Fundamental
    (2.0, 0.26),  # Octave
    (3.0, 0.04),  # Fifth
    (4.0, 0.81),  # Jawari cluster
    (5.0, 0.49),
    (6.0, 0.49),
    (7.0, 1.00),  # Dominant jawari peak
    (8.0, 0.24),
    (9.0, 0.54),  # Secondary peak
    (10.0, 0.34),
    (11.0, 0.45),
    (12.0, 0.08),
    (13.0, 0.07),
    (14.0, 0.04),
    (15.0, 0.03),
    (16.0, 0.05),
    (17.0, 0.33),  # Tertiary peak
    (18.0, 0.05),
    (19.0, 0.28),
    (20.0, 0.09),
]

# Jawari configuration — waveguide bridge termination
# Physical model: the string's displacement is reflected when it contacts the
# curved bridge surface. This nonlinear boundary creates the characteristic
# jawari buzz as an emergent property — upper harmonics are continuously
# regenerated by the bridge interaction rather than bolted on.
JAWARI_BRIDGE_HEIGHT = 0.3     # bridge distance from rest (lower = more jawari)
JAWARI_DAMPING = 0.999         # waveguide feedback coefficient (higher = longer sustain)

# Loop filter blend: controls brightness preservation in the waveguide.
# Standard Karplus-Strong uses 0.5 (averaging filter), which destroys upper
# harmonics over time. Tanpura needs much lower blend to preserve the bright
# jawari character (H4-H17 region).
# Per-pass gain at freq f = 1 - blend * (1 - cos(2πf/fs))
LOOP_FILTER_BLEND = 0.02      # 0.5 = original dark, 0.02 = bright


def generate_string_pluck(
    frequency, duration, amplitude_variation=1.0, volume=0.5
):
    """
    Generate a single string pluck using waveguide synthesis with bridge termination.

    A delay line (digital waveguide) models the vibrating string. The initial
    excitation is shaped to match the measured harmonic spectrum from a real
    Calcutta-standard tanpura. The bridge termination reflects the string's
    displacement when it goes below the bridge surface, creating the jawari
    buzz as an emergent physical property rather than an additive effect.

    The lowpass averaging filter (standard Karplus-Strong) models string
    damping, naturally attenuating upper harmonics over time. The bridge
    interaction continuously regenerates upper harmonics, counteracting
    the lowpass — this is what sustains the jawari character.
    """
    num_samples = int(SAMPLE_RATE * duration)
    t = np.arange(num_samples) / SAMPLE_RATE

    period = max(2, int(round(SAMPLE_RATE / frequency)))
    rng = np.random.RandomState(int(frequency * 100))

    # Shape initial excitation to match measured harmonic spectrum
    delay_line = np.zeros(period)
    for harmonic_num, amplitude in HARMONICS:
        if harmonic_num * frequency < SAMPLE_RATE / 2:
            phase = rng.uniform(0, 2 * np.pi)
            idx = np.arange(period)
            delay_line += amplitude * np.sin(
                2.0 * np.pi * harmonic_num * idx / period + phase
            )
    dl_peak = np.max(np.abs(delay_line))
    if dl_peak > 0:
        delay_line /= dl_peak

    # Waveguide with bridge termination (jawari)
    output = np.zeros(num_samples)
    read_pos = 0
    bridge = JAWARI_BRIDGE_HEIGHT

    for i in range(num_samples):
        y = delay_line[read_pos]
        output[i] = y

        # Bridge termination: reflect displacement off bridge surface
        if y < -bridge:
            y = -2.0 * bridge - y

        # Tunable lowpass + damping (modified Karplus-Strong)
        # Low blend preserves upper harmonics (brightness) unlike standard 0.5 averaging
        next_pos = (read_pos + 1) % period
        blend = LOOP_FILTER_BLEND
        delay_line[read_pos] = JAWARI_DAMPING * ((1 - blend) * y + blend * delay_line[next_pos])
        read_pos = next_pos

    # Remove DC offset from asymmetric bridge termination.
    output -= np.mean(output)

    # Add brief noise transient for realistic pluck attack
    noise_duration = int(0.03 * SAMPLE_RATE)  # 30ms
    noise = rng.randn(noise_duration) * 0.15
    noise_env = np.exp(-np.arange(noise_duration) / (0.01 * SAMPLE_RATE))
    output[:noise_duration] += noise * noise_env

    # Fast exponential attack matching real tanpura pluck (27ms measured 10-90% rise)
    attack_tau = 0.008  # ~8ms time constant
    attack = 1.0 - np.exp(-t / attack_tau)
    output *= attack * amplitude_variation * volume

    # Normalize to consistent level
    out_peak = np.max(np.abs(output))
    if out_peak > 0:
        output *= 0.8 / out_peak

    return output


def generate_tanpura_cycle(sa_frequency, string1_note):
    """Generate one complete 6-beat tanpura cycle as stereo audio."""
    ratio_note = string1_note  # Direct mapping: P, m, N

    # String frequencies: 1=variable lower octave, 2&3=tonic Sa, 4=lower Sa
    string1_freq = sa_frequency * NOTE_RATIOS[ratio_note] / 2.0
    string2_freq = sa_frequency
    string3_freq = sa_frequency
    string4_freq = sa_frequency / 2.0

    # Generate individual strings with different attack durations
    print(f"  Generating String 1 ({string1_note})...")
    string1_samples = generate_string_pluck(
        string1_freq, SUSTAIN_DURATION, amplitude_variation=0.98
    )

    print(f"  Generating String 2 (Sa)...")
    string2_samples = generate_string_pluck(
        string2_freq, SUSTAIN_DURATION, amplitude_variation=1.0
    )

    print(f"  Generating String 3 (Sa)...")
    string3_samples = generate_string_pluck(
        string3_freq, SUSTAIN_DURATION, amplitude_variation=1.0
    )

    print(f"  Generating String 4 (lower Sa)...")
    string4_samples = generate_string_pluck(
        string4_freq, SUSTAIN_DURATION, amplitude_variation=0.96
    )

    # Mix strings with traditional plucking pattern (beats: 1, -, 3, 4, 5, -)
    pluck_offsets = [0, 2, 3, 4]  # String1, String2, String3, String4
    all_strings = [string1_samples, string2_samples, string3_samples, string4_samples]

    # Create mono buffer for one complete cycle
    beat_interval_samples = int(SAMPLE_RATE * BEAT_INTERVAL)
    cycle_size = int(SAMPLE_RATE * CYCLE_DURATION)
    mono_buffer = np.zeros(cycle_size)

    # Mix all strings with their timing offsets
    for string_index, string_samples in enumerate(all_strings):
        offset = pluck_offsets[string_index] * beat_interval_samples
        for i in range(len(string_samples)):
            # Wrap around if string extends beyond cycle boundary
            buffer_index = (offset + i) % cycle_size
            mono_buffer[buffer_index] += string_samples[i]

    # Normalize mono buffer (leave headroom)
    max_amp = np.max(np.abs(mono_buffer))
    if max_amp > 0.85:
        mono_buffer *= 0.85 / max_amp

    # Create stereo with Haas effect (20ms delay)
    stereo_timing_offset = int(SAMPLE_RATE * 0.020)
    panning_l = 0.75
    panning_r = 0.75
    stereo_buffer = np.zeros((cycle_size, 2))

    for i in range(cycle_size):
        stereo_buffer[i, 0] = mono_buffer[i] * panning_l  # Left channel
        # Right channel with timing offset
        right_index = (i + stereo_timing_offset) % cycle_size
        stereo_buffer[i, 1] = mono_buffer[right_index] * panning_r

    # Final peak normalization (leave 10% headroom for DAC)
    actual_peak = np.max(np.abs(stereo_buffer))
    if actual_peak > 0:
        stereo_buffer *= 0.9 / actual_peak

    return stereo_buffer


def main():
    """Generate all tanpura audio files (OGG for Android, CAF for iOS)."""
    ogg_dir = Path(__file__).parent / "output" / "tanpura"
    caf_dir = Path(__file__).parent / "output" / "tanpura_caf"
    ogg_dir.mkdir(parents=True, exist_ok=True)
    caf_dir.mkdir(parents=True, exist_ok=True)

    total_files = len(SA_FREQUENCIES) * len(STRING1_NOTES)
    print(f"Generating {total_files} tanpura files in OGG + CAF formats...")
    print(f"  OGG → {ogg_dir}")
    print(f"  CAF → {caf_dir}")
    print()

    file_count = 0

    # Generate all combinations
    for sa_name, sa_freq in SA_FREQUENCIES.items():
        for string1_note in STRING1_NOTES:
            file_count += 1
            stem = f"{sa_name}_{string1_note}"

            print(f"[{file_count}/{total_files}] Generating {stem}...")
            print(f"  Sa = {sa_freq:.2f} Hz, String 1 = {string1_note}")

            audio_data = generate_tanpura_cycle(sa_freq, string1_note)

            _, tmp_name = tempfile.mkstemp(suffix=".wav")
            tmp_path = Path(tmp_name)
            try:
                sf.write(tmp_path, audio_data, SAMPLE_RATE, format="WAV", subtype="PCM_16")

                # OGG Vorbis via ffmpeg (max quality for spectrally dense waveguide output)
                subprocess.run(
                    [
                        "ffmpeg", "-y",
                        "-i", str(tmp_path),
                        "-c:a", "libvorbis",
                        "-q:a", "10",
                        str(ogg_dir / f"{stem}.ogg"),
                    ],
                    check=True,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                print(f"  ✓ OGG written")

                # CAF/ALAC (lossless) via macOS afconvert
                subprocess.run(
                    [
                        "afconvert",
                        str(tmp_path),
                        str(caf_dir / f"{stem}.caf"),
                        "-f", "caff",   # CAF container
                        "-d", "alac",   # Apple Lossless
                    ],
                    check=True,
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                print(f"  ✓ CAF written\n")
            finally:
                tmp_path.unlink(missing_ok=True)

    print(f"\n{'=' * 60}")
    print(f"Generation complete! {total_files} × 2 formats.")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
